#!/usr/bin/env bash
VERSION_NUMBER=0.2.0

usage() {
cat << EOF
Usage: growly [-hvt] command

Options:
    -t, --title     Set growlnotify title
    -h, --help      Show this message
    -v, --version   Show version
EOF
}

# Change long options to short
for arg
do
    delim=""
    case "$arg" in
        --title) args="${args}-t ";;
        --help) args="${args}-h ";;
        --version) args="${args}-v ";;
        *) [[ "${arg:0:1}" == "-" ]] || delim="\""
            args="${args}${delim}${arg}${delim} ";;
    esac
done
eval set -- $args

# Parse command line options.
while getopts "hvt:" option; do
    case "$option" in
        t) TITLE=$OPTARG;;    
        h) usage
           exit 0;;
        v) echo "`basename $0` $VERSION_NUMBER"
           exit 0;;
        # getopts issues an error message
        \?) usage >&2
           exit 1;;
    esac
done

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

# We want at least one non-option argument.
if [ $# -eq 0 ]; then
    usage >&2
    exit 1
fi

# Access additional arguments as usual through
# variables $@, $*, $1, $2, etc. or using this loop:
for PARAM; do
    COMMAND="$COMMAND $PARAM"
done

# Remove first space from command
COMMAND=${COMMAND:1:${#COMMAND}-1}

# Set a default title if one doesn't exist
if [ ! -n "$TITLE" ]; then
    TITLE="$COMMAND : $HOSTNAME"
fi

# Run the growl notification
growlnotify -m "`$COMMAND`" -t "$TITLE"
